server:
  port: ${PORT:8084}
  tomcat:
    max-http-form-post-size: 26MB
    max-swallow-size: 26MB

spring:
  application:
    name: application-service
  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 26MB
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/internship_application_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}
    prefer-ip-address: false
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
