server:
  port: ${PORT:8080}

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns:
              - ${CORS_ALLOWED_ORIGIN:http://localhost:5173}
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: false
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**, /skills/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

        - id: internship-service
          uri: lb://internship-service
          predicates:
            - Path=/internships/**

        - id: application-service
          uri: lb://application-service
          predicates:
            - Path=/applications/**

        - id: report-service
          uri: lb://report-service
          predicates:
            - Path=/reports/**

        - id: meeting-service
          uri: lb://meeting-service
          predicates:
            - Path=/meetings/**
          filters:
            - PreserveHostHeader

        - id: certificate-service
          uri: lb://certificate-service
          predicates:
            - Path=/certificates/**

        - id: chat-service-files
          uri: lb://chat-service
          predicates:
            - Path=/chats/files/**

        - id: chat-service
          uri: lb://chat-service
          predicates:
            - Path=/chats/**

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notifications/**

        - id: analytics-service
          uri: lb://analytics-service
          predicates:
            - Path=/analytics/**

        - id: recommendation-service
          uri: lb://recommendation-service
          predicates:
            - Path=/recommendations/**

        - id: ai-matcher
          uri: ${AI_MATCHER_URL:http://localhost:5000}
          predicates:
            - Path=/ai/**
          filters:
            - StripPrefix=1

jwt:
  secret: ${JWT_SECRET}

logging:
  level:
    org.springframework.cloud.gateway: INFO
    org.springframework.http.server.reactive: INFO
    org.springframework.web.reactive: INFO

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}
    prefer-ip-address: false
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
